// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: physics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for coffee pour simulation
type PourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId          string            `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PourId          string            `protobuf:"bytes,2,opt,name=pour_id,json=pourId,proto3" json:"pour_id,omitempty"`
	Origin          *Point2D          `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Intensity       float32           `protobuf:"fixed32,4,opt,name=intensity,proto3" json:"intensity,omitempty"`
	Viscosity       float32           `protobuf:"fixed32,5,opt,name=viscosity,proto3" json:"viscosity,omitempty"`
	NearbyStrokes   []*StrokeSnapshot `protobuf:"bytes,6,rep,name=nearby_strokes,json=nearbyStrokes,proto3" json:"nearby_strokes,omitempty"`
	SimulationSteps int32             `protobuf:"varint,7,opt,name=simulation_steps,json=simulationSteps,proto3" json:"simulation_steps,omitempty"`
}

func (x *PourRequest) Reset() {
	*x = PourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_physics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PourRequest) ProtoMessage() {}

func (x *PourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PourRequest.ProtoReflect.Descriptor instead.
func (*PourRequest) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{0}
}

func (x *PourRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PourRequest) GetPourId() string {
	if x != nil {
		return x.PourId
	}
	return ""
}

func (x *PourRequest) GetOrigin() *Point2D {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *PourRequest) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *PourRequest) GetViscosity() float32 {
	if x != nil {
		return x.Viscosity
	}
	return 0
}

func (x *PourRequest) GetNearbyStrokes() []*StrokeSnapshot {
	if x != nil {
		return x.NearbyStrokes
	}
	return nil
}

func (x *PourRequest) GetSimulationSteps() int32 {
	if x != nil {
		return x.SimulationSteps
	}
	return 0
}

// Response message containing stain results
type StainResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PourId          string            `protobuf:"bytes,1,opt,name=pour_id,json=pourId,proto3" json:"pour_id,omitempty"`
	StainPolygons   []*StainPolygon   `protobuf:"bytes,2,rep,name=stain_polygons,json=stainPolygons,proto3" json:"stain_polygons,omitempty"`
	StrokeMutations []*StrokeMutation `protobuf:"bytes,3,rep,name=stroke_mutations,json=strokeMutations,proto3" json:"stroke_mutations,omitempty"`
	ComputationMs   int32             `protobuf:"varint,4,opt,name=computation_ms,json=computationMs,proto3" json:"computation_ms,omitempty"`
}

func (x *StainResult) Reset() {
	*x = StainResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_physics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StainResult) ProtoMessage() {}

func (x *StainResult) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StainResult.ProtoReflect.Descriptor instead.
func (*StainResult) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{1}
}

func (x *StainResult) GetPourId() string {
	if x != nil {
		return x.PourId
	}
	return ""
}

func (x *StainResult) GetStainPolygons() []*StainPolygon {
	if x != nil {
		return x.StainPolygons
	}
	return nil
}

func (x *StainResult) GetStrokeMutations() []*StrokeMutation {
	if x != nil {
		return x.StrokeMutations
	}
	return nil
}

func (x *StainResult) GetComputationMs() int32 {
	if x != nil {
		return x.ComputationMs
	}
	return 0
}

// 2D point coordinates
type Point2D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point2D) Reset() {
	*x = Point2D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_physics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2D) ProtoMessage() {}

func (x *Point2D) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point2D.ProtoReflect.Descriptor instead.
func (*Point2D) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{2}
}

func (x *Point2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Stroke data for physics calculations
type StrokeSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrokeId string     `protobuf:"bytes,1,opt,name=stroke_id,json=strokeId,proto3" json:"stroke_id,omitempty"`
	Color    string     `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Width    float32    `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Points   []*Point2D `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	Opacity  float32    `protobuf:"fixed32,5,opt,name=opacity,proto3" json:"opacity,omitempty"`
}

func (x *StrokeSnapshot) Reset() {
	*x = StrokeSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_physics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrokeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrokeSnapshot) ProtoMessage() {}

func (x *StrokeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrokeSnapshot.ProtoReflect.Descriptor instead.
func (*StrokeSnapshot) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{3}
}

func (x *StrokeSnapshot) GetStrokeId() string {
	if x != nil {
		return x.StrokeId
	}
	return ""
}

func (x *StrokeSnapshot) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *StrokeSnapshot) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *StrokeSnapshot) GetPoints() []*Point2D {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *StrokeSnapshot) GetOpacity() float32 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

// Stain polygon result
type StainPolygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path    []*Point2D `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Opacity float32    `protobuf:"fixed32,3,opt,name=opacity,proto3" json:"opacity,omitempty"`
	Color   string     `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *StainPolygon) Reset() {
	*x = StainPolygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_physics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StainPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StainPolygon) ProtoMessage() {}

func (x *StainPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StainPolygon.ProtoReflect.Descriptor instead.
func (*StainPolygon) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{4}
}

func (x *StainPolygon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StainPolygon) GetPath() []*Point2D {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *StainPolygon) GetOpacity() float32 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

func (x *StainPolygon) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Stroke mutation from coffee absorption
type StrokeMutation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrokeId     string  `protobuf:"bytes,1,opt,name=stroke_id,json=strokeId,proto3" json:"stroke_id,omitempty"`
	ColorShift   string  `protobuf:"bytes,2,opt,name=color_shift,json=colorShift,proto3" json:"color_shift,omitempty"`
	BlurFactor   float32 `protobuf:"fixed32,3,opt,name=blur_factor,json=blurFactor,proto3" json:"blur_factor,omitempty"`
	OpacityDelta float32 `protobuf:"fixed32,4,opt,name=opacity_delta,json=opacityDelta,proto3" json:"opacity_delta,omitempty"`
}

func (x *StrokeMutation) Reset() {
	*x = StrokeMutation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_physics_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrokeMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrokeMutation) ProtoMessage() {}

func (x *StrokeMutation) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrokeMutation.ProtoReflect.Descriptor instead.
func (*StrokeMutation) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{5}
}

func (x *StrokeMutation) GetStrokeId() string {
	if x != nil {
		return x.StrokeId
	}
	return ""
}

func (x *StrokeMutation) GetColorShift() string {
	if x != nil {
		return x.ColorShift
	}
	return ""
}

func (x *StrokeMutation) GetBlurFactor() float32 {
	if x != nil {
		return x.BlurFactor
	}
	return 0
}

func (x *StrokeMutation) GetOpacityDelta() float32 {
	if x != nil {
		return x.OpacityDelta
	}
	return 0
}

var File_physics_proto protoreflect.FileDescriptor

var file_physics_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x22, 0x90, 0x02, 0x0a, 0x0b, 0x50, 0x6f, 0x75,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x68, 0x79,
	0x73, 0x69, 0x63, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x52, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x73, 0x63, 0x6f, 0x73, 0x69, 0x74, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x76, 0x69, 0x73, 0x63, 0x6f, 0x73, 0x69, 0x74, 0x79,
	0x12, 0x3e, 0x0a, 0x0e, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x6f, 0x6b,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x52, 0x0d, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x73,
	0x12, 0x29, 0x0a, 0x10, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x74, 0x65, 0x70, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x73, 0x69, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x0b,
	0x53, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f,
	0x75, 0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6c, 0x79,
	0x67, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f,
	0x6e, 0x73, 0x12, 0x42, 0x0a, 0x10, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x5f, 0x6d, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70,
	0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x4d, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x4d, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0x25, 0x0a,
	0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x79, 0x22, 0x9d, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x6f, 0x6b,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x6f,
	0x6b, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x12, 0x28, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x32, 0x44, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6f, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x22, 0x74, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x32, 0x44, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6f, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x94, 0x01, 0x0a, 0x0e, 0x53,
	0x74, 0x72, 0x6f, 0x6b, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x5f, 0x73, 0x68, 0x69, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x53, 0x68, 0x69, 0x66, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62,
	0x6c, 0x75, 0x72, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x62, 0x6c, 0x75, 0x72, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d,
	0x6f, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0c, 0x6f, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x74,
	0x61, 0x32, 0x4c, 0x0a, 0x0d, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x50, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x73, 0x12, 0x3b, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x53, 0x70, 0x72,
	0x65, 0x61, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x2e, 0x50, 0x6f,
	0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x68, 0x79, 0x73,
	0x69, 0x63, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_physics_proto_rawDescOnce sync.Once
	file_physics_proto_rawDescData = file_physics_proto_rawDesc
)

func file_physics_proto_rawDescGZIP() []byte {
	file_physics_proto_rawDescOnce.Do(func() {
		file_physics_proto_rawDescData = protoimpl.X.CompressGZIP(file_physics_proto_rawDescData)
	})
	return file_physics_proto_rawDescData
}

var file_physics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_physics_proto_goTypes = []interface{}{
	(*PourRequest)(nil),    // 0: physics.PourRequest
	(*StainResult)(nil),    // 1: physics.StainResult
	(*Point2D)(nil),        // 2: physics.Point2D
	(*StrokeSnapshot)(nil), // 3: physics.StrokeSnapshot
	(*StainPolygon)(nil),   // 4: physics.StainPolygon
	(*StrokeMutation)(nil), // 5: physics.StrokeMutation
}
var file_physics_proto_depIdxs = []int32{
	2, // 0: physics.PourRequest.origin:type_name -> physics.Point2D
	3, // 1: physics.PourRequest.nearby_strokes:type_name -> physics.StrokeSnapshot
	4, // 2: physics.StainResult.stain_polygons:type_name -> physics.StainPolygon
	5, // 3: physics.StainResult.stroke_mutations:type_name -> physics.StrokeMutation
	2, // 4: physics.StrokeSnapshot.points:type_name -> physics.Point2D
	2, // 5: physics.StainPolygon.path:type_name -> physics.Point2D
	0, // 6: physics.CoffeePhysics.ComputeSpread:input_type -> physics.PourRequest
	1, // 7: physics.CoffeePhysics.ComputeSpread:output_type -> physics.StainResult
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_physics_proto_init() }
func file_physics_proto_init() {
	if File_physics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_physics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_physics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StainResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_physics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point2D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_physics_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrokeSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_physics_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StainPolygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_physics_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrokeMutation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_physics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_physics_proto_goTypes,
		DependencyIndexes: file_physics_proto_depIdxs,
		MessageInfos:      file_physics_proto_msgTypes,
	}.Build()
	File_physics_proto = out.File
	file_physics_proto_rawDesc = nil
	file_physics_proto_goTypes = nil
	file_physics_proto_depIdxs = nil
}
