// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: physics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoffeePhysics_ComputeSpread_FullMethodName = "/physics.CoffeePhysics/ComputeSpread"
)

// CoffeePhysicsClient is the client API for CoffeePhysics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoffeePhysicsClient interface {
	ComputeSpread(ctx context.Context, in *PourRequest, opts ...grpc.CallOption) (*StainResult, error)
}

type coffeePhysicsClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeePhysicsClient(cc grpc.ClientConnInterface) CoffeePhysicsClient {
	return &coffeePhysicsClient{cc}
}

func (c *coffeePhysicsClient) ComputeSpread(ctx context.Context, in *PourRequest, opts ...grpc.CallOption) (*StainResult, error) {
	out := new(StainResult)
	err := c.cc.Invoke(ctx, CoffeePhysics_ComputeSpread_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoffeePhysicsServer is the server API for CoffeePhysics service.
// All implementations must embed UnimplementedCoffeePhysicsServer
// for forward compatibility
type CoffeePhysicsServer interface {
	ComputeSpread(context.Context, *PourRequest) (*StainResult, error)
	mustEmbedUnimplementedCoffeePhysicsServer()
}

// UnimplementedCoffeePhysicsServer must be embedded to have forward compatible implementations.
type UnimplementedCoffeePhysicsServer struct {
}

func (UnimplementedCoffeePhysicsServer) ComputeSpread(context.Context, *PourRequest) (*StainResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeSpread not implemented")
}
func (UnimplementedCoffeePhysicsServer) mustEmbedUnimplementedCoffeePhysicsServer() {}

// UnsafeCoffeePhysicsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeePhysicsServer will
// result in compilation errors.
type UnsafeCoffeePhysicsServer interface {
	mustEmbedUnimplementedCoffeePhysicsServer()
}

func RegisterCoffeePhysicsServer(s grpc.ServiceRegistrar, srv CoffeePhysicsServer) {
	s.RegisterService(&CoffeePhysics_ServiceDesc, srv)
}

func _CoffeePhysics_ComputeSpread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeePhysicsServer).ComputeSpread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeePhysics_ComputeSpread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeePhysicsServer).ComputeSpread(ctx, req.(*PourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoffeePhysics_ServiceDesc is the grpc.ServiceDesc for CoffeePhysics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeePhysics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "physics.CoffeePhysics",
	HandlerType: (*CoffeePhysicsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeSpread",
			Handler:    _CoffeePhysics_ComputeSpread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "physics.proto",
}
